# Generated by Django 5.2.12 on 2026-03-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('client_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('Divorce Consultation', 'Divorce Consultation'), ('Maintenance Hearing', 'Maintenance Hearing'), ('Civil Litigation', 'Civil Litigation'), ('Criminal Defense', 'Criminal Defense'), ('Estate Planning', 'Estate Planning'), ('Road Accident Fund', 'Road Accident Fund'), ('Other', 'Other')], max_length=50)),
                ('appointment_datetime', models.DateTimeField()),
                ('attorney', models.CharField(default='M. Makgetha', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-appointment_datetime'],
            },
        ),
    ]
