# Generated by Django 5.2.12 on 2026-03-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makgetha_appointment_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='attorney',
            field=models.CharField(choices=[('M. Makgetha', 'M. Makgetha')], default='M. Makgetha', max_length=100),
        ),
    ]
