# Generated by Django 5.2.12 on 2026-03-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makgetha_appointment_system', '0002_alter_appointment_attorney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('Divorce Matters', 'Divorce Matters'), ('Maintenance Matters', 'Maintenance Matters'), ('Civil Matters', 'Civil Matters'), ('Domestic Violence', 'Domestic Violence'), ('Harassment Matters', 'Harassment Matters'), ('Deceased Estate Matters', 'Deceased Estate Matters'), ('Road Accident Matters', 'Road Accident Matters'), ('Unlawful Arrests Matters', 'Unlawful Arrests Matters'), ('Immigration Matters', 'Immigration Matters'), ('Criminal Matters', 'Criminal Matters'), ('Other', 'Other')], max_length=50),
        ),
    ]
