# Generated by Django 5.2.12 on 2026-03-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makgetha_appointment_system', '0004_add_new_attorneys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='attorney',
            field=models.CharField(choices=[('Mr Makgetha', 'Mr Makgetha'), ('Mr Mbhalati', 'Mr Mbhalati'), ('Mr Tshitshiba', 'Mr Tshitshiba')], default='Mr Makgetha', max_length=100),
        ),
    ]
